---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kdm.fullname" . }}-clusterrole
  labels:
    {{- include "kdm.labels" . | nindent 4 }}
rules:
  - apiGroups: ["kdm.io"]
    resources: ["workspaces"]
    verbs: ["create", "delete", "update", "patch","get","list","watch"]
  - apiGroups: ["kdm.io"]
    resources: ["workspaces/status"]
    verbs: ["create", "delete", "update", "patch","get","list","watch"]
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["get","list","watch","update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","watch","create", "delete", "update", "patch"]
  - apiGroups: [ "" ]
    resources: [ "pods"]
    verbs: ["get","list","watch","create", "update", "patch" ]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get","list","watch","update", "patch"]
  - apiGroups: [ "apps" ]
    resources: ["deployments" ]
    verbs: ["get","list","watch","create", "delete","update", "patch"]
  - apiGroups: ["karpenter.sh"]
    resources: ["machines", "machines/status"]
    verbs: ["get","list","watch","create", "delete", "update", "patch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get","list","watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["update"]
    resourceNames: ["validation.webhook.kdm.io"]
