---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kaito.fullname" . }}-clusterrole
  labels:
    {{- include "kaito.labels" . | nindent 4 }}
rules:
  - apiGroups: ["kaito.sh"]
    resources: ["workspaces"]
    verbs: ["update", "patch","get","list","watch"]
  - apiGroups: ["kaito.sh"]
    resources: ["workspaces/status"]
    verbs: ["update", "patch","get","list","watch"]
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["get","list","watch","update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","watch","create", "delete", "update", "patch"]
  - apiGroups: [ "" ]
    resources: [ "pods"]
    verbs: ["get","list","watch","create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get","list","watch","create", "delete" ]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get","list","watch","update", "patch"]
  - apiGroups: [ "apps" ]
    resources: ["deployments" ]
    verbs: ["get","list","watch","create", "delete","update", "patch"]
  - apiGroups: [ "apps" ]
    resources: ["controllerrevisions" ]
    verbs: [ "get","list","watch","create", "delete","update", "patch"]
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets" ]
    verbs: [ "get","list","watch","create", "delete","update", "patch" ]
  - apiGroups: ["karpenter.sh"]
    resources: ["machines", "machines/status", "nodeclaims", "nodeclaims/status"]
    verbs: ["get","list","watch","create", "delete", "update", "patch"]
  {{- if eq .Values.cloudProviderName "azure" }}
  - apiGroups: [ "karpenter.azure.com" ]
    resources: [ "aksnodeclasses"]
    verbs: [ "get","list","watch","create", "delete", "update", "patch" ]
  {{- else if eq .Values.cloudProviderName "aws" }}
  - apiGroups: [ "karpenter.k8s.aws" ]
    resources: [ "ec2nodeclasses"]
    verbs: [ "get","list","watch","create", "delete", "update", "patch" ]
  {{- end }}
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get","list","watch"]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch", "create", "delete","update", "patch" ]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["update"]
    resourceNames: ["validation.workspace.kaito.sh"]
