apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.workspace.kaito.sh
  labels:
    {{- include "kaito.labels" . | nindent 4 }}
webhooks:
  - name: validation.workspace.kaito.sh
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "kaito.fullname" . }}
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.webhook.port }}
    failurePolicy: Fail
    sideEffects: None
    rules:
      - apiGroups:
          - kaito.sh
        apiVersions:
          - v1alpha1
        resources:
          - workspaces
        operations:
          - CREATE
          - UPDATE
