apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kaito.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
   {{- include "kaito.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kaito.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "kaito.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
