name: pr-e2e-test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore: ['docs/**', '**.md', '**.mdx', '**.png', '**.jpg']

env:
  GO_VERSION: "1.22"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run-e2e:
    strategy:
      fail-fast: false
      matrix:
        node-provisioner: [gpuprovisioner] # WIP: azkarpenter]
    permissions:
      contents: read
      id-token: write
      statuses: write
    uses: ./.github/workflows/e2e-workflow.yml
    with:
      git_sha: ${{ github.event.pull_request.head.sha }}
      node_provisioner: ${{ matrix.node-provisioner }}
